version: '3.8'  

services:
  nuxt-docker-example:
    container_name: my-container-nuxt
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"
    volumes:
      - .:/app 
    environment:
      - NODE_ENV=development 
